name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.103
    - name: Build with dotnet
      run: dotnet build AzureImageRecognition/AzureImageRecognition.sln --configuration Release
    - name: Cache
      uses: actions/cache@v1.1.2
      with:
        # A directory to store and save the cache
        path: cache
        # An explicit key for restoring and saving the cache
        key: "cache-key"
